multi-function-incorporation
Summary:

- Incorporation of auth logic into `any-sdk`.
- Incorporation of logging package into `any-sdk`.
- Incorporation of independent DTOs into `any-sdk`.
- Incorporation of some constants into `any-sdk`.
- GCloud OAuth included.
- Simple CLI support as a prelude to much more.
    - CLI simple test.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: Go
+name: Build
 
 on:
   push:
@@ -18,6 +18,7 @@ env:
   GOPRIVATE: github.com/stackql/*
   GH_ACCESS_TOKEN: ${{ secrets.ACTIONS_PRIVATE_PACKAGE_SECRET }}
   PLANCACHEENABLED: "true"
+  GOLANG_VERSION: 1.22
 
 jobs:
 
@@ -28,7 +29,7 @@ jobs:
     - name: Set up Go 1.x
       uses: actions/setup-go@v2
       with:
-        go-version: ^1.13
+        go-version: ^${{ env.GOLANG_VERSION }}
       id: go
 
     - name: Get rid of dissruptive line endings before checkout
@@ -73,7 +74,7 @@ jobs:
         Write-Output $BuildPlatform
         
         go build -x -v `
-          -o ostackqtool ./cmd/interrogate
+          -o build/anysdk ./cmd/interrogate
 
     - name: Test
       if: success()
@@ -86,7 +87,7 @@ jobs:
     - name: Set up Go 1.x
       uses: actions/setup-go@v2
       with:
-        go-version: ^1.13
+        go-version: ^${{ env.GOLANG_VERSION }}
       id: go
 
     - name: Check out code into the Go module directory
@@ -117,11 +118,24 @@ jobs:
         echo "BUILDPLATFORM: ${BUILDPLATFORM}"
 
         go build -x -v \
-          -o ostackqtool ./cmd/interrogate
+          -o build/anysdk ./cmd/interrogate
       
     - name: Test
       if: success()
       run: go test -timeout 240s -v ./...
+    
+    - name: CLI Test
+      if: success()
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y jq
+        result="$(build/anysdk const | jq -r '.ExtensionKeyAlwaysRequired')"
+        if [ "$result" != "x-alwaysRequired" ]; then
+          echo "CLI Test Failed with unexpected result: $result"
+          exit 1
+        else
+          echo "CLI Test passed with expected result: $result"
+        fi
 
   macosbuild:
     name: MacOS Build
@@ -130,7 +144,7 @@ jobs:
     - name: Set up Go 1.x
       uses: actions/setup-go@v2
       with:
-        go-version: ^1.13
+        go-version: ^${{ env.GOLANG_VERSION }}
       id: go
 
     - name: Check out code into the Go module directory
@@ -163,7 +177,7 @@ jobs:
         echo "BUILDPLATFORM: ${BUILDPLATFORM}"
 
         go build -x -v \
-          -o ostackqtool ./cmd/interrogate
+          -o build/anysdk ./cmd/interrogate
 
     - name: Test
       if: success()
@@ -176,7 +190,7 @@ jobs:
     - name: Set up Go 1.x
       uses: actions/setup-go@v2
       with:
-        go-version: ^1.16
+        go-version: ^${{ env.GOLANG_VERSION }}
       id: go
 
     - name: Check out code into the Go module directory
@@ -210,4 +224,4 @@ jobs:
 
         GOOS=darwin GOARCH=arm64 \
         go build -x -v \
-          -o ostackqtool ./cmd/interrogate
+          -o build/anysdk ./cmd/interrogate
